@extends('layouts.index')
@section('content')
                    <section class="box special">
                        <header class="major">
                            <h2>Our Solution</h2>
                            <p>
                                Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.
                            </p>

                            <p>
                                Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.
                            </p>

                            <p>
                                Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.
                            </p>

                            <p>
                                Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.Being a parent, we always worried about what our children eat at school. Sometimes even school provides student with junk food. It has no nutritional value and bad for their health.
                            </p>
                        </header>
                        <span class="image featured"><img src="{{ asset('images/fa-healthy-school-lunch.jpg') }}" alt="" /></span>
                    </section>
@endsection